### ISSUE TITLE
Mobile UI looks broken

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#101]
**Describe the bug**

The card content layout doesn't look good on mobile on mobile when the speaker name or job title is long, or when there are 2 language tags.

**To Reproduce**

Open the speaker list on mobile (with production data or dummy data that has long speaker names / 2 language tags)

**Expected behavior**

Better responsive mobile UI. Probably stacking languages tags below the name.

**Screenshots**

<img src="https://user-images.githubusercontent.com/1096046/92003489-0d1db600-ed7c-11ea-9783-c2a00d399682.png" height="700" /> <img src="https://user-images.githubusercontent.com/1096046/92003524-1b6bd200-ed7c-11ea-82b9-bdb7c9f1933b.png" height="700" />

**Comment by ann-kilzer** [comment]
Solving as part of #115
