### ISSUE TITLE
"スピーカーを指名する" sounds different meaning from "nominate a speaker"

### ISSUE THREAD

**Issue by wakanapo** [WWCodeTokyo/speak-her-db#103]
**Describe the bug**
"スピーカーを指名する" sounds like appointing someone as a speaker. However, the button is for registration as a speaker. 

**Expected behavior**
I think the text should be "スピーカーになる", "スピーカーを推薦する", "スピーカーに立候補する" or "スピーカーにノミネートする".

**Comment by ann-kilzer** [comment]
Thanks for filing. @Ania-chan Would you be able to take a look, at your convenience?

**Comment by Ania-chan** [comment]
@ann-kilzer sure! I'm planning to look at the remaining translations today after work 👍
