### ISSUE TITLE
Japanese Localization

### ISSUE THREAD

**Issue by shokokb** [WWCodeTokyo/speak-her-db#113]
**Is your feature request related to a problem? Please describe.**
From: WWCodeTokyo From:Tutti-san
> Looking for help with a Japanese translation check for https://speakher.jp, would anyone be able to help?

**Describe the solution you'd like**

1. Japanese translation check for https://speakher.jp
2. Send pull-request to Tutti-san

**Comment by shokokb** [comment]
- Checkout: master 
- Target file: ja.json
- Branch:113 - japanese-localization

**Questions to Developer Team**
There is many vocabularies in Japanese about “speaker”

- 講演者（Kouensha -Speaker、Presenter, Reacher including professors & social infruencers）*General
- 講師（Koushi - Teacher, Tutor in eluding professors & social influencers）

If you have some impression about Japanese words, please let me know your intention. I’ll pick up some.

**Comment by ann-kilzer** [comment]
We've actually had a couple PRs related to internationalization since Tutti made that slack request, but if you find specific examples on the site where the wording could be improved, feel free to comment or open a PR.

#89 
#100 
#105
