### ISSUE TITLE
Allow secondary company / affiliation in nominate form

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#117]
**Is your feature request related to a problem? Please describe.**
Some users have requested the ability to add professional affiliations such as Academic institutions, volunteer positions, or second jobs.

**Describe the solution you'd like**
Please add the ability to submit `secondary_title` and `secondary_affiliation`

**Describe alternatives you've considered**
Would it make sense to have more than two? 

**Additional context**

**Comment by RossellaFer** [comment]
Can I work on this? :)

**Comment by ann-kilzer** [comment]
The column names are provided above, which should be a helpful breadcrumb until #137 is ready.

**Comment by RossellaFer** [comment]
Thanks @ann-kilzer !
In terms of language, I was thinking about using the following:

```
        "affiliation": {
            "title": "Secondary Role",
            "company": "Organization",
            "hint": "Academic institutions, volunteer positions, or second jobs"
        },
```

<img width="994" alt="affiliations" src="https://user-images.githubusercontent.com/39148794/93221544-dcd90d00-f7a8-11ea-8f48-cd8aae6f85a0.png">

Can someone help with the JP translations?

**Comment by ann-kilzer** [comment]
Looks good. No need for the JP translations to hold up the PR, as vue-i18n will fall back to English if Japanese is missing. @Ania-chan might be able to help with translation.

**Comment by Ania-chan** [comment]
@ann-kilzer should I make Japanese translations now and make a PR to this PR or wait until this PR is merged?

**Comment by ann-kilzer** [comment]
Either way is fine. We can update the base branch if the translations take longer. Thanks again for your help @Ania-chan

**Comment by tuttiq** [comment]
@Ania-chan the PR is merged, feel free to open a new one for translation :)
