### ISSUE TITLE
Contact email has no speaker name or id

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#135]
There's a bug in the contact form where the speaker name or id is not being linked to the message. Instead, the message shows `Speaker: undefined`.

![bug_speaker_ref](https://user-images.githubusercontent.com/1096046/93023041-27328080-f627-11ea-9567-ffc3fe5769d1.png)

**Comment by ann-kilzer** [comment]
I see another occurrence of this from Sept. 1, inside the Netlify data. Looks like that person was just using our tool to say hello, but it would be good to fix this asap so we're ready for making connections.
