### ISSUE TITLE
Improve contact form with a message template

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#136]
The contact form to contact speakers has no instructions right now, but we could use some basic information to moderate the contact requests and make sure we only redirect sincere messages to our speakers.

Idea: add a template or placeholder to the message field on the contact form. 

Placeholder example: _"Please introduce yourself and describe briefly the topic you want to talk about with the Speaker. We will moderate and redirect your message to the speaker as soon as possible"_  

Template example:
```
Name:
Brief self-introduction:
Describe the topic you want to talk about with the speaker:
```

**Comment by RossellaFer** [comment]
Can I take this one?

**Comment by ann-kilzer** [comment]
Consistent hint is interesting, but one issue is it disappears as soon as the user starts typing. Another option is to actually set an initial value with a template, i.e. set the message value to some default and validate that the user edits it. We might consider what type of content would help prompt a good message. 

Goals of this feature are:
- Communicate for the purpose of inviting the speaker to give a presentation
- Convey the what, when, where, who...
- Introduce the two parties

Non-goals:
- Casual chat, "hello" messages, other networking (we've gotten a few of these)
- Spam or anything against code of conduct 😆  (we got a solicitation for a Palm Kernel processing machine, lol)

Perhaps something like:

"Please introduce yourself to the speaker, providing details of your event (who, what, when, where), and how they might be a good match."

Feel free to come up with something else, too. 

You might also want to add a "clear" feature if auto-fill the field.

**Comment by ann-kilzer** [comment]
We'll be removing the contact form in #241
