### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#139]
- [x] Code of Conduct
- [ ] Translation into Japanese

**Comment by tuttiq** [comment]
Who should we ask for Japanese translation? This is kind of a big translation task. Should we have a separate issue so we can close this one?

**Comment by tuttiq** [comment]
Created a separate ticket for translation: https://github.com/WWCodeTokyo/speak-her-db/issues/148
