### ISSUE TITLE
N+1 query for Topics on SpeakerCard (FindSpeaker view)

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#144]
**Describe the issue**
Our caching logic is not working, so SpeakerCard > CardFooter is querying for the whole list of topics from Airtable for every single speaker card.

**To Reproduce**
1. Go to the site homepage (Find Speaker)
2. Open the Network inspector on your browser
3. Check how many requests for `Topics?All` are being made

**Improved behavior**
- Quick short-term solution: move the request to the FindSpeaker view and pass it down as props to the SpeakerCard > CardFooter component.
- Better solution: [implement proper caching on the front-end using state management (Vuex)](https://github.com/WWCodeTokyo/speak-her-db/issues/146).

**Comment by ann-kilzer** [comment]
![Uploading SpeakHer.png…]()

**Comment by ann-kilzer** [comment]
<img width="1469" alt="SpeakHer" src="https://user-images.githubusercontent.com/4602369/94706986-db4d3e80-037d-11eb-8687-2ca9aca7fbec.png">

**Comment by tuttiq** [comment]
It's fixed in the PR above.
