### ISSUE TITLE
[Japanese translation] Code of Conduct

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#148]
Missing translation task of https://github.com/WWCodeTokyo/speak-her-db/issues/139

Code of Conduct that needs to be translated:
https://github.com/WWCodeTokyo/speak-her-db/blob/master/CODE_OF_CONDUCT.md

PR where the CoC was added (for context): https://github.com/WWCodeTokyo/speak-her-db/pull/129

**Comment by ann-kilzer** [comment]
This project is now in maintenance mode, so I'm going to close some of these feature issues due to lack of resources. 🙏
