### ISSUE TITLE
Link to previous speaking videos on speaker profile

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#151]
**Is your feature request related to a problem? Please describe.**

This idea is a suggestion from the wider community:
"One feature I'd love to see, if you have the time to make it, would be to add clips (YouTube, audio etc) of your members speaking at events before. 

[One speaker], for example, was brilliant when she came on our podcast (and in many other appearances as well), and I feel like having links to past speaking engagements will make people more likely to be booked again in the future."

**Describe the solution you'd like**
Add a field to link to a prior presentation. It could be a url to youtube or similar, and validated as a URL.

**Describe alternatives you've considered**
Open to other ideas as well!

**Additional context**

**Comment by RageZBla** [comment]
I am working on this in PR #161
