### ISSUE TITLE
As a visitor, I should see the logos of publications that SpeakHer has been featured in.

### ISSUE THREAD

**Issue by yanarchy** [WWCodeTokyo/speak-her-db#155]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
* When I go to the home page
* I should see the logos of publications underneath the hero section
* When I click on a logo, it should open the article or press link in a new tab

**Describe alternatives you've considered**
We could also change the location of this.

**Comment by ann-kilzer** [comment]
A carousel might be a good way of saving space but also showing this on the main page. I am hoping we get lots of press!

Another idea is to show a preview then link to another page, similar to the About page.
