### ISSUE TITLE
As a user, I should see links to SpeakHer social media on the homepage

### ISSUE THREAD

**Issue by yanarchy** [WWCodeTokyo/speak-her-db#156]
**Describe the solution you'd like**
We should have Instagram + Twitter logos (and maybe Facebook) linking them to our social media accounts. This should ideally be either in the header or footer.

Twitter: twitter.com/speakherjapan
Instagram: https://www.instagram.com/speakherjp/

**Comment by dominikeinkemmer** [comment]
How about something like this in the header? (could also be after the language switcher 

![image](https://user-images.githubusercontent.com/18051009/94984121-b4605980-0583-11eb-88fc-d217a09841c4.png)


Or maybe after the language switcher looks better? 🤔 
![image](https://user-images.githubusercontent.com/18051009/94984135-e2459e00-0583-11eb-9bb1-b8ac3229e055.png)

**Comment by ann-kilzer** [comment]
Let me handle this one please, thanks.
