### ISSUE TITLE
Fix Netlify PR status checks

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#160]
**Describe the bug**
Netlify PR status checks are missing

**To Reproduce**
1. Create a new PR
2. Notice there is no longer a deploy preview

**Expected behavior**
I miss it.

**Comment by tuttiq** [comment]
Netlify has a protection against deploying PRs that are not opened directly on our repo :) (to prevent malicious scripts from accessing our production deploy configs)

But we as admins can go to the Netlify dashboard and allow the deploy if we trust the PR, then the preview will be generated.
