### ISSUE TITLE
Make it more clear that it's possible to self-nominate

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#163]
### Is your feature request related to a problem? Please describe
We've had many people ask if they can nominate themselves or need to have someone else nominate them. "Submitter" fields being mandatory, some people don't think they can input "self" or their own name.

### Describe the solution you'd like
- Add a persistent-hint to "Submitter" field with a text `Please write your name if is the submitter is yourself`
- Add some kind of title/description at the top of the form to make it clear you can nominate yourself OR someone else

### Describe alternatives you've considered
I've considered making the submitter field optional, but I think it's better to keep it mandatory to guarantee we have the information when it's *not* a self-nomination.

### Additional context
The solution described was a suggestion from a user when she gave me the feedback :)

**Comment by ann-kilzer** [comment]
Good suggestion. We could also add a checkbox to indicate "I am nominating myself" and then auto-populate the fields.
