### ISSUE TITLE
Add loading component to start page

### ISSUE THREAD

**Issue by dominikeinkemmer** [WWCodeTokyo/speak-her-db#168]
**Describe the solution you'd like**
Currently the start page looks a bit blank while it's loading the results from the database. I thought maybe adding a small loading animation below `Find a speaker` might be a nice touch to the UX so the user sees that some information is fetched right now. 

**Describe alternatives you've considered**
It could also be a full page overlay but I think that's overkill and would prevent users from interacting with the page in case they just want to go straight to nominating a speaker.

We could also use an extra library and not use vuetify's existing loader component. This one has a lot of fancy animations for example, not sure if it's not overkill though 😅 
https://github.com/epicmaxco/epic-spinners

**Additional context**
Simple example with build in loaders of vuetify

(gif is a bit faster than actual page load, would have to play with the recording's fps settings I think 😅 ):

![loading_spinner](https://user-images.githubusercontent.com/18051009/94983709-55e5ac00-0580-11eb-938b-81d7d5595306.gif)

One of the fancier spinners from the [epic-spinners](https://github.com/epicmaxco/epic-spinners) component
![loading_spinner-2](https://user-images.githubusercontent.com/18051009/94983901-a4477a80-0581-11eb-8780-ddc98a621b8c.gif)

**Comment by ann-kilzer** [comment]
This is a great suggestion. Let's stick with a simple circle spinner following the material styles. I like the previews, but I would suggest adding some negative space above and below the spinner for visual balance. Feel free to open a PR.
