### ISSUE TITLE
Remove native Language name on SpeakerCard tags

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#176]
### Is your feature request related to a problem? Please describe.
There's not much value in showing the native language name in the SpeakerCard. It actually makes the language labels longer (because we have to show it in English as well).

![Screen Shot 2020-10-04 at 10 13 31 PM](https://user-images.githubusercontent.com/1096046/95016603-f629f680-068e-11eb-9b91-6afc5ee25f9f.png)

### Describe the solution you'd like
- [ ] Remove the `native` language name showing on the SpeakerCard and show only `name_en` for now. In the future we should [localize language names to Japanese](https://github.com/WWCodeTokyo/speak-her-db/issues/190) as well.
- [ ] Keep it as is for the Nomination form (`[name_en] - [native]`).

## Describe alternatives you've considered
~None. Open to suggestions/discussion.~ Discussion below.

**Comment by tuttiq** [comment]
This issue requires production database migration, so it can only be completed by one of the Airtable admins (@tuttiq , @ann-kilzer or @yanarchy )

**Comment by ann-kilzer** [comment]
🤔  I borrowed this pattern from Google Chrome.
One of the challenges is that languages vary wildly in what they call one another (eg. german vs. Deutsch vs. allemande), and someone with limited English skills might be more likely to recognize their language in its native localization. We've also got an ongoing initiative to expand the languages supported by this site since #88 

I'd like to hear more user feedback before we decide to undo this.

This doesn't add a lack of Japanese translation, we just never implemented that. We certainly could add a column for the Japanese name, but it would take some work.

**Comment by ann-kilzer** [comment]
One more thought -- perhaps we should just keep it in the Input form, but omit it from the Speaker card. It does look to be a bit overkill there.

**Comment by tuttiq** [comment]
I understand the initiative, but I'd say expanding support to many languages other than Japanese and English right now is a bit of a scope creep? If/when we do that we may have to rethink all models that have `name_en` and `name_ja` fields right now, I think that's a future discussion we shouldn't get into right now (especially because it's probably a very small percentage of our audience that don't understand either Japanese or English).

In any case, I do think we should look into adding the Japanese translation for the languages, and then have the site use either `[name_en] - [native]` or `[name_ja] - [native]` if the locale is Japanese.

And I like the idea of keeping this format on the nomination form and removing the native name on the SpeakerCard 👍

**Comment by tuttiq** [comment]
@ann-kilzer Let me know if you're fine with this ☝️ direction I'll update the issue description to remove the native name only on the speaker card and open another ticket for adding the Japanese translation of the language names.

**Comment by ann-kilzer** [comment]
Yeah I didn't mean right away, that would be a diversion, but if someone enthusiastic comes along and wants to translate things into Korean, Chinese, etc., it could be a cool opportunity to reach other communities.

Just to clarify:

For the Speaker cards: v0: Let's update the tags to just show the language in English. v1: Use ja or en depending on selected locale

For the Nomination form: v0: keep as is v1: `[name_en] - [native]` or `[name_ja] - [native]` depending on locale

Airtable: v0: keep as is v1: add Japanese translation of language names

**Comment by tuttiq** [comment]
Probably a good idea to split in two separate tickets, since they can be done separately? Let me transform this one on v0 and create a second one for v1.

**Comment by tuttiq** [comment]
Final specs for this issue:
- Remove the native language name showing on the SpeakerCard and show only name_en for now. In the future we should localize language names to Japanese as well.
 - Keep it as is for the Nomination form ([name_en] - [native]).
