### ISSUE TITLE
Add tooltip to SpeakerCard icon links

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#177]
### Is your feature request related to a problem? Please describe.
Some icons on SpeakerCard are not obvious what they mean/link to.

![Screen Shot 2020-10-04 at 12 21 28 AM](https://user-images.githubusercontent.com/1096046/95016768-068ea100-0690-11eb-8772-624d842fd483.png)

### Describe the solution you'd like
Add a tooltip on-hover for the icons with a label to what they mean (E.g. "Website", "Presentation video")
Ref: [Vuetify tooltip](https://vuetifyjs.com/en/components/tooltips/#usage)

![tooltip_example](https://user-images.githubusercontent.com/1096046/95016819-684f0b00-0690-11eb-92ec-ed870853421c.gif)

### Describe alternatives you've considered
A text label for each link, but may get too long? Tooltips don't show on mobile though.

**Comment by ann-kilzer** [comment]
So the trouble with tooltips is they don't work on mobile at all. I get that there is an ambiguity between website and video links now. Perhaps text buttons for those will reduce the mystery meat?

**Comment by tuttiq** [comment]
I'd be fine with text labels as long as the design looks good with them 👍

**Comment by theyokohamalife** [comment]
Hey! Is this a feature you'd still like to have implemented?
