### ISSUE TITLE
Make Japanese name optional on nomination form

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#178]
### Is your feature request related to a problem? Please describe.
Not all foreigners want or know how to translate their names to Japanese characters, it shouldn't be mandatory.

![Screen Shot 2020-10-04 at 10 44 08 PM](https://user-images.githubusercontent.com/1096046/95017224-283d5780-0693-11eb-91a2-cfd8db285952.png)

### Describe the solution you'd like
- [ ] Remove required validation from the Japanese name input
- [ ] Make sure the site falls back to English names if the Japanese name is blank (when the locale is 日本語)
    - [ ] SpeakerCard
    - [ ] Contact speaker feature

### Describe alternatives you've considered
I've considered a logic where we make either English or Japanese name optional, as long as you have the other one, but I think it adds unnecessary complexity and prevents users using the site in English to read Japanese names in kanji/kana if there's no English name available. I also assume most (all?) Japanese people know how to romanize their names, so my suggestion is to keep English name mandatory and make Japanese name optional.

### Additional context
I personally never use my name in katakana anywhere unless it's mandatory (and I usually hate when it is). If someone using the site in Japanese copies and pastes my katakana name on Google to find more about me, they will probably find nothing. I'd rather have my alphabet name in both languages. Maybe other people have the same preference?

**Comment by ann-kilzer** [comment]
I have a concern about this change, as it could shift the site more towards English speakers and away from Japanese speakers. If you live here, you'll have to know your name in kana. I don't think it's too much to ask people to enter that. What do you think?

**Comment by ann-kilzer** [comment]
Temporarily removing the good first issue tag until we make a decision.

**Comment by tuttiq** [comment]
> I have a concern about this change, as it could shift the site more towards English speakers and away from Japanese speakers.

Hmmmm, I don't see how making one field in the form mandatory or optional would make a difference in our target audience? This change does not have to affect in any way our marketing and target audience for our communication.

> If you live here, you'll have to know your name in kana. I don't think it's too much to ask people to enter that.
> One thing we could do is provide a link to a service that translates names into Kana, for people who are new to Japan.

I think it just makes the form harder to fill, increasing the risk of drop outs. Especially if someone doesn't yet have a Japanese keyboard installed on their device, it basically becomes a blocker to submitting the form.

**Comment by ann-kilzer** [comment]
I suppose Japanese-language-only event organizers wouldn't really be looking for Gaijin who can't speak Japanese anyway. And you make a good point about mobile users.

Okay! We can make it optional.

**Comment by RageZBla** [comment]
@ann-kilzer @tuttiq may I work on this issue?

**Comment by ann-kilzer** [comment]
@RageZBla Please do 😄
