### ISSUE TITLE
Add pagination component

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#180]
Follow up ticket for this comment:

you mean a specific component for speaker pagination? Yeah I can add it in a separate PR together with improved spacing of the arrows :)

_Originally posted by @dominikeinkemmer in https://github.com/WWCodeTokyo/speak-her-db/pull/166#discussion_r499326765_

**Comment by dominikeinkemmer** [comment]
You can assign me to this issue, I'll work on it this week :)

**Comment by dominikeinkemmer** [comment]
ah this can be closed I think :)
