### ISSUE TITLE
Translate secondary affiliation fields

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#193]
Please provide Japanese translation for the following strings:

"Pronouns"
"Please type in your pronouns if yours are not listed"
"Secondary Role"
"Academic institutions, volunteer positions, or second jobs"
"(Secondary) Organization"

It's okay to provide these as a comment and then someone else can make the code change. See screenshot below for context, or visit: https://speakher.jp/nominate-speaker
(Google / Machine translation unacceptable for this task, please only work on this if you are fluent.)

**Comment by ann-kilzer** [comment]
Here's a screenshot in context: 

<img width="1060" alt="SpeakHer" src="https://user-images.githubusercontent.com/4602369/95733725-7d91ee00-0cbd-11eb-9c7b-50511242cd99.png">

**Comment by shokokb** [comment]
次の文字列の日本語訳を入力してください。

"Pronouns" 
 → 第一人称
"Please type in your pronouns if yours are not listed" 
 → 適切な第一人称がない場合は、入力してください。
"Secondary Role"
 →第二の職業の職名
"Academic institutions, volunteer positions, or second jobs"
 →学術組織、ボランティア、副業
"(Secondary) Organization"
 →第二の所属組織(副業)

If you use the word "the main position ", it's possible to use "the substitute position".
1) ポジション
2) サブポジション

**Comment by Kimmym6a** [comment]
How about these?

Original
<img width="599" alt="Screen Shot 2021-02-11 at 23 50 17" src="https://user-images.githubusercontent.com/22512115/107652478-f7fe6900-6cc3-11eb-81ca-7ecb377f3347.png">

Translated
<img width="602" alt="Screen Shot 2021-02-11 at 23 50 07" src="https://user-images.githubusercontent.com/22512115/107652554-0b113900-6cc4-11eb-90d9-5ffbeed85bfd.png">

We don't have a writing "pronounce" culture. Then I added some explanation to explain the reason which understandable.

**Comment by ann-kilzer** [comment]
Thanks for the comments, @Kimmym6a and @shokokb. Kimmy-san, would it be possible to share your suggested translations as text in addition to the photo? Sometimes I have to look up individual kanji to read.

Just looking at this again, we should ask someone in the LGBT community for assistance translating the pronouns section. It is a new cultural development, and people can feel very sensitive about their gender identity. A direct translation from "she/her" to 彼女 might not capture the nuance of how a person wishes to be described. I know some people to ask.

Feel free to propose translations for fields outside the pronouns section! Thanks

**Comment by Kimmym6a** [comment]
Hi @ann-kilzer , sorry for the late feedback.

>would it be possible to share your suggested translations as text in addition to the photo? 
Sure! Just in time, I wrote all of them down below.

>we should ask someone in the LGBT community for assistance translating the pronouns section
This is the best way, Thank you!

>A direct translation from "she/her" to 彼女 might not capture the nuance of how a person wishes to be described
It is why I added the explanation as a translation.（掲載メディア等で〜）

**Translation suggestions**

Pronouns: 第三人称のご希望
Please type in pronouns if you are not listed: 掲載メディア等でご紹介する際の第三人称のご希望をお聞かせください。

職名：ご職業
Primary Occupation: 具体的なご職業（本業）をお書きください。

会社：会社名

Secondary role: 経歴（その他）
Academic institutions, volunteer positions, or second jobs. : 学術研究、ボランティア、副業など、その他の経歴をお書きください。

Organization: 所属先（その他）
