### ISSUE TITLE
[COPY UPDATE] Change all instances of `female` to `women`

### ISSUE THREAD

**Issue by yanarchy** [WWCodeTokyo/speak-her-db#196]
Whoops, this got overlooked! Thought it already got fixed previously.

Mostly having to do with the titles/headers on the main page. We should aim for more inclusive language by using the adjective women instead of female.

Female has anatomical inferences, which isn't inclusive for people who are trans, etc., and the culture is shifting towards using woman as the descriptive.

**Comment by ann-kilzer** [comment]
Thanks for filing! 🌈

**Comment by ann-kilzer** [comment]
something like `sed -i 's/female/woman/g' * && git commit -a -m " ¯\_(ツ)_/¯" && git push`... 😆
