### ISSUE TITLE
[Backend migration] API fetch endpoints

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#224]
Part of https://github.com/WWCodeTokyo/speak-her-db/issues/138 implementing a Rails backend to replace Airtable.

Implement REST endpoints to fetch all resources:
- [x] GET `/topics` => returns all topics
- [x] GET `/locations` => returns all locations (prefectures)
- [x] GET `/spoken_languages` => returns all speaker language options
- [ ] GET `/speakers` => returns all speakers
    - [ ] support pagination
    - [ ] support the current search/filter capability

**Comment by ann-kilzer** [comment]
This project is now in maintenance mode, so I'm going to close some of these feature issues due to lack of resources. 🙏
