### ISSUE TITLE
[Backend migration] Implement a visual Admin interface

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#225]
Airtable is very convenient because we have a visual interface to check and manipulate the database easily. Migrating to our own server and database means we would have to ssh into the server and query the database manually anytime we want to do the same thing.

My suggestion is to implement a visual Admin interface for easy manipulation of the database by the project admins (@ann-kilzer , @yanarchy and @tuttiq ). Rails has some convenient libraries to easily implement something like that:

- [ActiveAdmin](https://activeadmin.info/) seems to be the most popular
- [Rails Admin](https://github.com/sferik/rails_admin) comes in second place
- [Administrate](https://github.com/thoughtbot/administrate) is the third place

Popularity ranking reference: https://www.ruby-toolbox.com/categories/rails_admin_interfaces

**Comment by ann-kilzer** [comment]
This project is now in maintenance mode, so I'm going to close some of these feature issues due to lack of resources. 🙏
