### ISSUE TITLE
[Backend migration] Migrate emails and automations from Zapier to Rails

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#226]
As we migrate from Airtable to our own Rails backend, we should probably migrate the automated notifications from Zapier to Rails.

Rails has built-in emailing features that we can easily setup with Gmail's SMTP server (using our speakher gmail address to send the emails), so I recommend we use that.

- [Rails Guides: ActionMailer Basics](https://guides.rubyonrails.org/action_mailer_basics.html)

**Comment by ann-kilzer** [comment]
Closing due to #241
