### ISSUE TITLE
[Backend migration] Nominate speaker endpoint

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#227]
Implement the nominate speaker endpoint on the Rails API.

- POST `/speakers` with the speaker info payload => should create an **unpublished** speaker on the database

Follow-up TODOs addressed on separate issues:
- Creating a new speaker should trigger a notification email (#226 Migrate email automation from Zapier to Rails)
- We should be able to publish speaker entries from the Admin interface (#225 Implement a visual Admin interface)

**Comment by ann-kilzer** [comment]
This project is now in maintenance mode, so I'm going to close some of these feature issues due to lack of resources. 🙏
