### ISSUE TITLE
Implement Search feature

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#32]
We have a `Search` component, but we need to define the specs of how the search should work and implement it.

For an MVP version could be implemented on the front-end, since we have the whole list of speakers on the front-end and we can easily search the list without any queries to the database.

Later on, when we have pagination, we'll probably need to query the database to find the result(s).

**Comment by ann-kilzer** [comment]
We'll need to re-enable the Search.vue component disabled in #48

**Comment by ann-kilzer** [comment]
Let's work on pagination #124 before implementing search.

**Comment by tuul-wq** [comment]
@tuttiq could you assign this task to me?
