### ISSUE TITLE
Improve Speaker Card

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#92]
**Is your feature request related to a problem? Please describe.**
The speaker card doesn't show all the information we've collected yet. 

**Describe the solution you'd like**
Speaker card should display other fields such as
- Second job / association (one suggestion was this could be academic affiliation for PhDs)
- Biography
- Social links
- Photo?
- Pronouns after #91

**Comment by tuttiq** [comment]
Ideas:

- Show SNS buttons as rounded icons near the speaker name (that means moving the language tag somewhere else)

- Show 1~2 lines of the speaker bio on the card and truncate. Add an expandable arrow to expand the card and show the rest of the text

- Alternatively (maybe improvement after MVP?), create a Speaker Profile page, with the profile picture (if it exists) and all the information, including full speaker bio (this would be great if we have a unique URL per speaker, so people can also share the direct link to a specific profile)
