### ISSUE TITLE
Show additional speaker info on the card (urls, speaker bio)

### ISSUE THREAD

**Issue by tuttiq** [WWCodeTokyo/speak-her-db#94]
We already collect this info but don't show anywhere on the list right now.

Ideas:
- Show SNS buttons as rounded icons near the speaker name (that means moving the language tag somewhere else)

- Show 1~2 lines of the speaker bio on the card and truncate. Add an expandable arrow to expand the card and show the rest of the text

- Alternatively (maybe improvement after MVP?), create a Speaker Profile page, with the profile picture (if it exists) and all the information, including full speaker bio (this would be great if we have a unique URL per speaker, so people can also share the direct link to a specific profile)

**Comment by ann-kilzer** [comment]
Duplicate of #92 ？ I was planning on doing some mockups this week.

**Comment by ann-kilzer** [comment]
Love the suggestions btw

**Comment by tuttiq** [comment]
Ah, good catch! I'll put the ideas there and close this one!
